name: ansible
on:
  push:
    branches:
      - main
    paths:
      - ansible
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Ansible ci/cd"
