name: frontend
# run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
    paths:
      - frontend/**
jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # TODO: https://stackoverflow.com/questions/65412663/github-actions-stuck-on-yarn-build-step-for-react-app-continous-integration
      # - name: Cache Dependencies
      #   uses: actions/cache@v3
      #     with:
      #       path: '**/node_modules'
      #       key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd frontend install

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd frontend build

      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd frontend test

      # TODO: https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
      # - name: Cache Docker layers
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: klammrock/frontend:latest

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
          script: |
            sudo docker pull klammrock/frontend
            sudo docker stop frontend
            sudo docker rm frontend
            sudo docker run -p 80:80 -d --name frontend --network="klammrock" klammrock/frontend
            sudo docker update --restart=always frontend
